//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MuhasebeEntities2 : DbContext
    {
        public MuhasebeEntities2()
            : base("name=MuhasebeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TABLEMUSTERİ> TABLEMUSTERİ { get; set; }
        public DbSet<TABLESIPARIS> TABLESIPARIS { get; set; }
        public DbSet<TABLOKATEG> TABLOKATEG { get; set; }
        public DbSet<URUNİSİMLERİ> URUNİSİMLERİ { get; set; }
        public DbSet<SIPARISLER> SIPARISLER { get; set; }
    
        public virtual ObjectResult<US_ADETLERI_Result> US_ADETLERI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<US_ADETLERI_Result>("US_ADETLERI");
        }
    
        public virtual ObjectResult<SORGU_Result> SORGU()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SORGU_Result>("SORGU");
        }
    
        public virtual ObjectResult<GELİRTABLO_Result> GELİRTABLO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GELİRTABLO_Result>("GELİRTABLO");
        }
    }
}
