//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIPARISLER
    {
        public SIPARISLER()
        {
            this.TABLESIPARIS = new HashSet<TABLESIPARIS>();
        }
    
        public int SIPARISID { get; set; }
        public string BAŞLIK { get; set; }
        public string NO { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public Nullable<int> CARİID { get; set; }
        public Nullable<bool> ONAY { get; set; }
    
        public virtual ICollection<TABLESIPARIS> TABLESIPARIS { get; set; }
        public virtual TABLEMUSTERİ TABLEMUSTERİ { get; set; }
    }
}
