//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLOKATEG
    {
        public TABLOKATEG()
        {
            this.TABLESIPARIS = new HashSet<TABLESIPARIS>();
            this.URUNİSİMLERİ = new HashSet<URUNİSİMLERİ>();
        }
    
        public int CINSID { get; set; }
        public string CINSADI { get; set; }
    
        public virtual ICollection<TABLESIPARIS> TABLESIPARIS { get; set; }
        public virtual ICollection<URUNİSİMLERİ> URUNİSİMLERİ { get; set; }
    }
}
