//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLEMUSTERİ
    {
        public TABLEMUSTERİ()
        {
            this.TABLESIPARIS = new HashSet<TABLESIPARIS>();
            this.SIPARISLER = new HashSet<SIPARISLER>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string TELEFON { get; set; }
        public Nullable<double> BAKİYE { get; set; }
        public Nullable<double> ALACAK { get; set; }
    
        public virtual ICollection<TABLESIPARIS> TABLESIPARIS { get; set; }
        public virtual ICollection<SIPARISLER> SIPARISLER { get; set; }
    }
}
