//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNİSİMLERİ
    {
        public URUNİSİMLERİ()
        {
            this.TABLESIPARIS = new HashSet<TABLESIPARIS>();
        }
    
        public int URUNADI_ID { get; set; }
        public Nullable<int> CINS { get; set; }
        public string URUNADI { get; set; }
        public Nullable<int> STOK_ADEDİ { get; set; }
        public Nullable<double> BİRİM_FİYAT { get; set; }
        public Nullable<double> ALIŞ_FİYAT { get; set; }
    
        public virtual ICollection<TABLESIPARIS> TABLESIPARIS { get; set; }
        public virtual TABLOKATEG TABLOKATEG { get; set; }
    }
}
